=== UCLALibrary/sinai_metadata/data-model/jsonschemas/agent.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/agent.json",
    "title": "Agent",
    "description": "A record for an agent, either an individual or an organization, capable of acting in the production of material objects or creation of conceptual works",
    "type": "object",
    "properties": {
        "ark": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
        },
        "type": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/agent_types"
        },
        "pref_name": {
            "type": "string",
            "minLength": 1
        },
        "alt_name": {
            "type": ["array", "null"],
            "items": {
                "type": "string",
                "minLength": 1
            },
            "unevaluatedItems": false        
        },
        "desc": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/summary"
        },
        "gender": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/genders"
        },
        "birth": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/date_core",
            "unevaluatedProperties": false
        },
        "death": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/date_core",
            "unevaluatedProperties": false
        },
        "floruit": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/date_core",
            "unevaluatedProperties": false
        },
        "rel_con": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/rel_con"
            },
            "unevaluatedItems": false
        },
        "bib": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/bib.json"
            },
            "unevaluatedItems": false
        },
        "note": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/note.json"
            },
            "unevaluatedItems": false
        },
        "assoc_name": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_name.json"
            },
            "unevaluatedItems": false
        },
        "assoc_place": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_place.json"
            },
            "unevaluatedItems": false
        },
        "cataloguer": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/cataloguer"
            },
            "unevaluatedItems": false
        }
    },
    "required": [
        "ark",
        "type",
        "pref_name"
    ],
    "unevaluatedProperties": false
}

=== UCLALibrary/sinai_metadata/portal_data/agents/s1h01q.json
{
    "ark": "ark:/21198/s1h01q",
    "type": "person",
    "pref_name": "Diadochus of Photice",
    "alt_name": [
        "Diadochus, Bishop of Photice, active 5th century"
    ],
    "gender": "Man",
    "floruit": {
        "value": "active 5th century",
        "iso": {
            "not_before": "0401",
            "not_after": "0500"
        }
    },
    "rel_con": [
        {
            "label": "Diadochus, Bishop of Photice, active 5th century",
            "uri": "http://viaf.org/viaf/32806504",
            "source": "VIAF"
        },
        {
            "label": "Diadochus Photicensis",
            "uri": "https://pinakes.irht.cnrs.fr/notices/auteur/895/",
            "source": "Pinakes"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/agents/s1g595.json
{
    "ark": "ark:/21198/s1g595",
    "type": "person",
    "pref_name": "Antiochus of Sulcis",
    "alt_name": [],
    "gender": "Man",
    "floruit": {
        "value": "active 1st century-2nd century",
        "iso": {
            "not_before": "0001",
            "not_after": "0200"
        }
    },
    "rel_con": [
        {
            "label": "Antiochus, of Sulcis, Saint, active 1st century-2nd century",
            "uri": "http://viaf.org/viaf/73357861",
            "source": "VIAF"
        }
    ]
}
