=== UCLALibrary/sinai_metadata/data-model/jsonschemas/layer.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/layer.json",
    "title": "Inscribed Layer",
    "type": "object",
    "properties": {
        "ark": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
        },
        "reconstruction": {
            "type": "boolean"
        },
        "state": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/states_layer"
        },
        "label": {
            "type": "string",
            "minLength": 1
        },
        "locus": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
        },
        "summary": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/summary"
        },
        "extent": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/extent"
        },
        "writing": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/writing.json"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "ink": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/ink.json"
            },
            "unevaluatedItems": false
        },
        "layout": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/layout.json"
            },
            "unevaluatedItems": false
        },
        "text_unit": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                    },
                    "label": {
                        "type": "string",
                        "minLength": 1
                    },
                    "locus": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
                    }
                },
                "required": [
                    "id",
                    "label"
                ],
                "unevaluatedProperties": false
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "para": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/paracontent.json"
            },
            "unevaluatedItems": false
        },
        "assoc_date": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_date.json"
            },
            "unevaluatedItems": false
        },
        "assoc_name": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_name.json"
            },
            "unevaluatedItems": false
        },
        "assoc_place": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_place.json"
            },
            "unevaluatedItems": false
        },
        "features": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
            },
            "unevaluatedItems": false
        },
        "related_mss": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/related_mss.json"
            },
            "unevaluatedItems": false
        },
        "note": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/note.json"
            },
            "unevaluatedItems": false
        },
        "bib": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/bib.json"
            },
            "unevaluatedItems": false
        },
        "cataloguer": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/change_log_entry"
            },
            "unevaluatedItems": false
        },
        "parent": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "internal": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "unevaluatedItems": false
        }
    },
    "required": [
        "ark",
        "reconstruction",
        "state",
        "label",
        "writing",
        "text_unit",
        "parent"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1t907.json
{
    "ark": "ark:/21198/s1t907",
    "reconstruction": false,
    "label": "Sinai Arabic 497, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1mt0j",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        },
        {
            "id": "deco-vegetative",
            "label": "Decoration, Vegetative"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "11th c.",
            "iso": {
                "not_before": "1001",
                "not_after": "1100"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Knotted vine headpieces between ff.62v-141r; f. 63r, arch"
        }
    ],
    "parent": [
        "ark:/21198/z1bk2x0s"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1vc9n.json
{
    "ark": "ark:/21198/s1vc9n",
    "reconstruction": false,
    "label": "Sinai Arabic 449, Overtext (Undetermined (Arabic))",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "arabic-undetermined",
                    "label": "Undetermined (Arabic)",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1p065",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "13th c.",
            "iso": {
                "not_before": "1201",
                "not_after": "1300"
            }
        }
    ],
    "parent": [
        "ark:/21198/z1tt5v70"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1734d.json
{
    "ark": "ark:/21198/s1734d",
    "reconstruction": false,
    "label": "Sinai Syriac 30, Undertext (Greek majuscule)",
    "locus": "ff. 142, 144, 147, 149",
    "state": {
        "id": "undertext",
        "label": "Undertext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "greek-maj",
                    "label": "Greek majuscule",
                    "writing_system": "Greek"
                }
            ],
            "note": [
                "Biblical majuscule | Similar to Vindob. theol. gr. 31, Paris. suppl. gr. 1286, and Codex Purpureus Rossanensis, suggesting a date in the sixth century (501-600 CE) and a place of origin in the region of Syria or Antioch (cf. G. Cavallo, Ricerche sulla maiuscola biblica (Florence, 1967), pp. 98-104; P. Orsini, Manoscritti in maiuscola biblica. Materiali per un aggiornamento (Cassino, 2005), pp. 176-177, 201-203, 210-211"
            ]
        }
    ],
    "layout": [
        {
            "columns": "2 columns",
            "lines": "25 lines"
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1w404",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "6th c. ",
            "iso": {
                "not_before": "0501",
                "not_after": "0600"
            }
        }
    ],
    "assoc_place": [
        {
            "value": "Syria or Antioch",
            "event": {
                "id": "origin",
                "label": "Place of Origin"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "Reconstructed folio order, ff. 142r, 142v, 144v, 144r, 147v, 147r, 149r, 149v"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Description of undertext by Pasquale Orsini"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Bibliography: R. L. Bensly, J. R. Harris, and F. C. Burkitt, The Four Gospels in Syriac Transcribed from the Sinaitic Palimpsest (Cambridge, 1894), p. xvi ; Α. S. Lewis, Select Narratives of Holy Women: From the Syro-Antiochene or Sinai palimpsest as written above the old Syriac Gospels by John Stylite, of Beth-mari-qanūn in A.D. 778, I, Syriac text (London, 1900), pp. 45-46 ; A. Hjelt (ed.), Syrus sinaiticus, Helsingfors 1930, p. 15 ; C. Guignard, “0323: A Forgotten 4th or 5th Century Greek Fragment of the Gospel of John in the Syrus Sinaiticus,” Novum Testamentum 57 (2015), pp. 311-319 ; The original quaternion must have been as follows: I (142rv), II (144vr), III (folio lost), IV (folio lost) | V (folio lost), VI (folio lost), VII (147vr), VIII (149rv)"
        }
    ],
    "parent": [
        "ark:/21198/z12n5hwt"
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/layers/s1c02v.json
{
    "ark": "ark:/21198/s1c02v",
    "reconstruction": false,
    "label": "Sinai Arabic 311, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s15m1t",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "11th c.",
            "iso": {
                "not_before": "1001",
                "not_after": "1100"
            }
        }
    ],
    "parent": [
        "ark:/21198/z1b86xkt"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1z325.json
{
    "ark": "ark:/21198/s1z325",
    "reconstruction": false,
    "label": "Sinai Arabic 254, Overtext (Undetermined (Arabic))",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "arabic-undetermined",
                    "label": "Undetermined (Arabic)",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1rq0r",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "colophon",
            "label": "Colophon"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "f. 39v",
            "lang": [
                {
                    "id": "arab1395",
                    "label": "Arabic"
                }
            ],
            "assoc_date": [
                {
                    "type": {
                        "id": "origin",
                        "label": "Date of Origin"
                    },
                    "value": "15 Ab 7240 (adam) :: 1732 (AD)"
                }
            ],
            "note": [
                "Attested places:  Mount Sinai ; City of David, Bethlehem"
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "1732",
            "iso": {
                "not_before": "1732"
            }
        }
    ],
    "parent": [
        "ark:/21198/z1xs6zqg"
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/layers/s12925.json
{
    "ark": "ark:/21198/s12925",
    "reconstruction": false,
    "label": "Sinai Syriac NF M 11, Undertext (Christian Palestinian Aramaic)",
    "locus": "ff. 65–66, 97–104",
    "state": {
        "id": "undertext",
        "label": "Undertext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "cpa",
                    "label": "Christian Palestinian Aramaic",
                    "writing_system": "Syriac"
                }
            ],
            "note": [
                "Early large CPA"
            ]
        }
    ],
    "layout": [
        {
            "columns": "2 columns",
            "lines": "24 lines"
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1q97z",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "6th-7th c. ",
            "iso": {
                "not_before": "0501",
                "not_after": "0700"
            }
        }
    ],
    "assoc_place": [
        {
            "value": "Possibly St. Catherine's Monastery",
            "event": {
                "id": "origin",
                "label": "Place of Origin"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "Reconstructed folio order, ff. 101r, 102v, 100v, 99r, 100r, 99v, 101v, 102r, 104r, 103v, 97v, 98r, 97r, 98v, 104v, 103r, 66v, 65r, 66r, 65v"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Description of undertext by Christa Müller-Kessler"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Bibliography: Philothée, pp. 300-302; 303-305 (by A. Desreumaux)"
        }
    ],
    "parent": [
        "ark:/21198/r1vd6wc9"
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/layers/s1s32m.json
{
    "ark": "ark:/21198/s1s32m",
    "reconstruction": false,
    "label": "Sinai Arabic 553, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1kq06",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "colophon",
            "label": "Colophon"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "ff. 132r-132v",
            "lang": [
                {
                    "id": "arab1395",
                    "label": "Arabic"
                }
            ],
            "as_written": "كان الفراغ من نسخة في ثلاث ساعات مضت من نهار يوم السبت لواحد وعشرين يوما خلت من أيلول سنة ستة آلاف وستمائة واثنين وثمانين للعالم وسنة ألف وأربعمائة وخمسة وثمانين للملك الإسكندر اليوناني وسنة ألف ومائه واثنين وثمانين لربنا المسيح وسنة وتسعة وستين وخمسمائة للهجرة رحم الله قرأ وسمع ودعا لكاتبها الحقير…بن اليس إسحاق ابن الخوري يوحنا الطبشراني غفر الله له ولوالديه ولجميع بني المعمودية",
            "assoc_date": [
                {
                    "type": {
                        "id": "origin",
                        "label": "Date of Origin"
                    },
                    "value": "Saturday 21 Aylul 6682 (world) :: 1485 (Seleucid) ::  1182 (Christ) :: 569 (hijra)"
                }
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "1182",
            "iso": {
                "not_before": "1182"
            }
        }
    ],
    "parent": [
        "ark:/21198/z15t546z"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s12883.json
{
    "ark": "ark:/21198/s12883",
    "reconstruction": false,
    "label": "Sinai Arabic 151, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ],
            "note": [
                "Kufic elements"
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1vw72",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "border-deco",
            "label": "Border(s), Decorative"
        },
        {
            "id": "deco-geometric",
            "label": "Decoration, Geometric"
        },
        {
            "id": "colophon",
            "label": "Colophon"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "ff. 186v-187r",
            "lang": [
                {
                    "id": "arab1395",
                    "label": "Arabic"
                }
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "867",
            "iso": {
                "not_before": "0867"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Red borders throughout, beginning on f. 9v"
        },
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Cross, f. 16r"
        },
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Quire signatures with geometric decoration ff. 4r, 12r, 20r, 28r, 36r, 84r, 92r, 100r, 108r, 116r, 148r, 156r, 164r, 180r; numerical, ff .229, 237r, 245r, 253r"
        }
    ],
    "parent": [
        "ark:/21198/z1vx1kvk"
    ]
}
