=== UCLALibrary/sinai_metadata/data-model/jsonschemas/layer.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/layer.json",
    "title": "Inscribed Layer",
    "type": "object",
    "properties": {
        "ark": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
        },
        "reconstruction": {
            "type": "boolean"
        },
        "state": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/states_layer"
        },
        "label": {
            "type": "string",
            "minLength": 1
        },
        "locus": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
        },
        "summary": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/summary"
        },
        "extent": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/extent"
        },
        "writing": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/writing.json"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "ink": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/ink.json"
            },
            "unevaluatedItems": false
        },
        "layout": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/layout.json"
            },
            "unevaluatedItems": false
        },
        "text_unit": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                    },
                    "label": {
                        "type": "string",
                        "minLength": 1
                    },
                    "locus": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
                    }
                },
                "required": [
                    "id",
                    "label"
                ],
                "unevaluatedProperties": false
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "para": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/paracontent.json"
            },
            "unevaluatedItems": false
        },
        "assoc_date": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_date.json"
            },
            "unevaluatedItems": false
        },
        "assoc_name": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_name.json"
            },
            "unevaluatedItems": false
        },
        "assoc_place": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_place.json"
            },
            "unevaluatedItems": false
        },
        "features": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
            },
            "unevaluatedItems": false
        },
        "related_mss": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/related_mss.json"
            },
            "unevaluatedItems": false
        },
        "note": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/note.json"
            },
            "unevaluatedItems": false
        },
        "bib": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/bib.json"
            },
            "unevaluatedItems": false
        },
        "cataloguer": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/change_log_entry"
            },
            "unevaluatedItems": false
        },
        "parent": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "internal": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "unevaluatedItems": false
        }
    },
    "required": [
        "ark",
        "reconstruction",
        "state",
        "label",
        "writing",
        "text_unit",
        "parent"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1b918.json
{
    "ark": "ark:/21198/s1b918",
    "reconstruction": false,
    "label": "Sinai Syriac 196, Overtext (Melkite)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "melkite",
                    "label": "Melkite",
                    "writing_system": "Syriac"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s14t1k",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "deco-vegetative",
            "label": "Decoration, Vegetative"
        },
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        },
        {
            "id": "colophon",
            "label": "Colophon"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "253r-253v",
            "lang": [
                {
                    "id": "class1252",
                    "label": "Syriac"
                }
            ],
            "as_written": "ܐܬܟܬܒ ܘܐܫܬܡܠܝ ܟܬܒܐ ܗܢܐ ܝܘܡ ܕ̄: ܒ̄ܝܐ ܡܢ ܝܪܚ ܐܕܪ. ܒܫܢܬ ܫܬܐ ܐܠܦܝܢ ܘܬܡܢܐܐ ܡܐܐ ܘܚܕܐ ܠܐܒܘܢ ܐܕܡ܀܀ ܘܡܢ ܫܢܝܐ ܕܐܠܟܣܢܕܪܘܣ. ܐܠܦ ܘܫܬܡܐܐ ܘܐܪܒܥ܀ ܐܝܟ ܪܠܗܕܕܐ ܘܬܫ̄ܒܘ ܘܐܝܩܪܐ ܕܬܠܝܠܝ̄ܘ ܩܕܝܫܬܐ ܘܫܘܝܬ ܒܐܘܣܝܐ ܕܐܒܐ ܘܒܪܐ ܘܪܘܚܐ ܕܩܘܕܫܐ܀ ܐܬܟܬܒ ܒܕܝܪܐ ܩܕܝܫܐ ܛܘܪ ܣܝܢܝ ܠܥܕܬܐ ܩܕܝܫܬܐ ܕܝܠܕܬ ܐܠܗܐ ܒܕܝܪܐ ܡܩܕܝܫܐ܀ ܒܐܝܕܝ ܐܢܫܐ ܚܛܝܐ ܘܕܘܐܡܢ ܟܠܢܫ ܘܠܐ ܫܘܐ ܕܢܬܩܪܐ ܫܡܗ܆ ܟܗܢܐ ܫܡܥܘܢ ܒܪ ܝܘܣܦ..",
            "assoc_name": [
                {
                    "value": "Shem'un bar Yosef",
                    "as_written": "ܫܡܥܘܢ ܒܪ ܝܘܣܦ",
                    "role": {
                        "id": "scribe",
                        "label": "Scribe"
                    }
                }
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "1292",
            "iso": {
                "not_before": "1292"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Headpieces, knotted vine, f. 113v; ff. 55r, f. 171, red and black"
        }
    ],
    "parent": [
        "ark:/21198/z1wt0bw1"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1v33m.json
{
    "ark": "ark:/21198/s1v33m",
    "reconstruction": false,
    "label": "Sinai Syriac 223, Overtext (Melkite)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "melkite",
                    "label": "Melkite",
                    "writing_system": "Syriac"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1nq3z",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "13th c.",
            "iso": {
                "not_before": "1201",
                "not_after": "1300"
            }
        }
    ],
    "parent": [
        "ark:/21198/z1rv2dzm"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s14k62.json
{
    "ark": "ark:/21198/s14k62",
    "reconstruction": false,
    "label": "Sinai Arabic 270, Overtext (Undetermined (Arabic))",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "arabic-undetermined",
                    "label": "Undetermined (Arabic)",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1z65b",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "deco-geometric",
            "label": "Decoration, Geometric"
        },
        {
            "id": "illustration",
            "label": "Illustration(s)"
        },
        {
            "id": "colophon",
            "label": "Colophon"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "f. 469r",
            "lang": [
                {
                    "id": "arab1395",
                    "label": "Arabic"
                }
            ],
            "as_written": "كان الفراغ من نساخة هذا الكتاب المبارك وهو من أقوال أبينا النبيل في القديسين باسيليوس الكبير في العاشر من شهر آذار سنة سبعة آلاف ومائة ثلثة وثلثين لكون العالم وكتب في دير طور سيناء المقدس في أيام رئاسة الأب الأقدس والإناء الطاهر المقدس السيد الاسقف كير يواصف أدام الرب الاله رئاسته وكاتبة العبد الأثيم والمرء الدميم  سيماون باسم شماس من مدينة حمص المحروسة ويبتهل ويتضرع لكل من قرأ فيه ووجد شيء من النقص والغلط وأصلحه يصلح الرب أحواله وقد جعله بان يكون بعد عينه وقفا على الدير المذكور فكل من سرقة أو اختلسه يكون تحت لعنات الأباء الثلاثمائة وثمانية عشر ويكون النبي العظيم ماري موسى خصمه فالويل ثم الويل لمن رضي لنفسه ذلك",
            "assoc_date": [
                {
                    "type": {
                        "id": "origin",
                        "label": "Date of Origin"
                    },
                    "value": "10 Adhar 7133 (creation)"
                }
            ],
            "note": [
                "Attested places:  Mount Sinai"
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "1625",
            "iso": {
                "not_before": "1625"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Illustration of a figure with headpiece holding a vessel with radial markings surrounding both on f. 245r | Geometric tailpiece, f. 244v | Geometric decoration, f. 469r"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Manicule, f. 324v, in red ink, f. 366r, in black ink"
        }
    ],
    "parent": [
        "ark:/21198/z1p85g5s"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1t04n.json
{
    "ark": "ark:/21198/s1t04n",
    "reconstruction": false,
    "label": "Sinai Syriac 9, Overtext (Estrangela)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "estrangela",
                    "label": "Estrangela",
                    "writing_system": "Syriac"
                }
            ]
        }
    ],
    "layout": [
        {
            "columns": "2 columns"
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1mm3m",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "8th c.",
            "iso": {
                "not_before": "0701",
                "not_after": "0800"
            }
        }
    ],
    "parent": [
        "ark:/21198/z18k8ttz"
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/layers/s14m1h.json
{
    "ark": "ark:/21198/s14m1h",
    "reconstruction": false,
    "label": "Sinai Greek 699, Undertext (Greek minuscule)",
    "locus": "f. 81",
    "state": {
        "id": "undertext",
        "label": "Undertext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "greek-min",
                    "label": "Greek minuscule",
                    "writing_system": "Greek"
                }
            ]
        }
    ],
    "layout": [
        {
            "columns": "1 columns",
            "lines": "20 lines"
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1sm35",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "11th c. ",
            "iso": {
                "not_before": "1001",
                "not_after": "1100"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "Reconstructed folio order, ff. 81v (right side), 81r (left side), 81r (right side), 81v (left side)"
        },
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "The current fol. 81 was a bifolio (recto 270 degrees, verso 90 degrees) and therefore it consists of two folios (1 = left portion of fol. 81r / right portion of fol. 81v; 2 = right portion of fol. 81r / left portion of fol. 81v [only the inner half is preserved])"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Description of undertext by Pasquale Orsini"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Bibliography: Abbreviations for editions are as follows: Pent = Πεντηκοστάριον, ed. P. Vitali (Rome, 1738) ; PeR = Πεντηκοστάριον χαρμόσυνον (Rome, 1883) ; PeV = Πεντηκοστάριον (Venice, 1875)"
        }
    ],
    "parent": [
        "ark:/21198/z11n8grf"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1mw3c.json
{
    "ark": "ark:/21198/s1mw3c",
    "reconstruction": false,
    "label": "Sinai Arabic 199, Overtext (Undetermined (Arabic), Thuluth)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "arabic-undetermined",
                    "label": "Undetermined (Arabic)",
                    "writing_system": "Arabic"
                },
                {
                    "id": "thuluth",
                    "label": "Thuluth",
                    "writing_system": "Arabic"
                }
            ],
            "note": [
                "Sections headings written in thuluth: f. 1v, 10r, 13v, 14r, 18r, 23v, 25v, 26v, 28v, 30r, 33r, 52v, 54v, 60v, 65v, 70v, 75v, 81r, 84v, 86r, 88r, 94v, 99r, 102v, 129v, 132r, 135v, 142r"
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1fh2n",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        },
        {
            "id": "deco-geometric",
            "label": "Decoration, Geometric"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "18th c.",
            "iso": {
                "not_before": "1701",
                "not_after": "1800"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "contents",
                "label": "Contents Note"
            },
            "value": "Greek text, f. 45r"
        },
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Minor geometric headpieces, red dot and floral motif ff. 14v, 18r, 33r; black dot work f. 35r"
        }
    ],
    "parent": [
        "ark:/21198/z1vh6s4d"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1831k.json
{
    "ark": "ark:/21198/s1831k",
    "reconstruction": false,
    "label": "Sinai Arabic 95, Overtext (Undetermined (Arabic))",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "arabic-undetermined",
                    "label": "Undetermined (Arabic)",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s12p9m",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "border-deco",
            "label": "Border(s), Decorative"
        },
        {
            "id": "border",
            "label": "Border(s)"
        },
        {
            "id": "deco-architectural",
            "label": "Decoration, Architectural"
        },
        {
            "id": "deco-calligraphic",
            "label": "Decoration, Calligraphic"
        },
        {
            "id": "deco-full-page",
            "label": "Decoration, Full-page"
        },
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        },
        {
            "id": "deco-geometric",
            "label": "Decoration, Geometric"
        },
        {
            "id": "deco-vegetative",
            "label": "Decoration, Vegetative"
        },
        {
            "id": "table",
            "label": "Table(s)"
        },
        {
            "id": "colophon",
            "label": "Colophon"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "ff. 340ar-340av",
            "lang": [
                {
                    "id": "arab1395",
                    "label": "Arabic"
                }
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "1277",
            "iso": {
                "not_before": "1277"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Ornate bordered headpiece with decorative calligraphy, vegetal, vine and floral motif down in the negative, red ink, ff.75v, 130v, 224v, without calligraphy, 285v"
        },
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Ornate arched table, bordered by vegetative and floral vine motif and alternating geometric patterns, ff.127v-128r, 219v-221v, with minimal border and geometric decoration, f. 284v"
        }
    ],
    "parent": [
        "ark:/21198/z1vq4mbb"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1w32j.json
{
    "ark": "ark:/21198/s1w32j",
    "reconstruction": false,
    "label": "Sinai Arabic 520, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1pm2v",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        },
        {
            "id": "deco-geometric",
            "label": "Decoration, Geometric"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "10th c.",
            "iso": {
                "not_before": "0901",
                "not_after": "1000"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Minor geometric headpieces throughout, beginning on f. 11r"
        }
    ],
    "parent": [
        "ark:/21198/z1c26f13"
    ]
}
