=== UCLALibrary/sinai_metadata/data-model/jsonschemas/layer.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/layer.json",
    "title": "Inscribed Layer",
    "type": "object",
    "properties": {
        "ark": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
        },
        "reconstruction": {
            "type": "boolean"
        },
        "state": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/states_layer"
        },
        "label": {
            "type": "string",
            "minLength": 1
        },
        "locus": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
        },
        "summary": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/summary"
        },
        "extent": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/extent"
        },
        "writing": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/writing.json"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "ink": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/ink.json"
            },
            "unevaluatedItems": false
        },
        "layout": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/layout.json"
            },
            "unevaluatedItems": false
        },
        "text_unit": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                    },
                    "label": {
                        "type": "string",
                        "minLength": 1
                    },
                    "locus": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
                    }
                },
                "required": [
                    "id",
                    "label"
                ],
                "unevaluatedProperties": false
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "para": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/paracontent.json"
            },
            "unevaluatedItems": false
        },
        "assoc_date": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_date.json"
            },
            "unevaluatedItems": false
        },
        "assoc_name": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_name.json"
            },
            "unevaluatedItems": false
        },
        "assoc_place": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_place.json"
            },
            "unevaluatedItems": false
        },
        "features": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
            },
            "unevaluatedItems": false
        },
        "related_mss": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/related_mss.json"
            },
            "unevaluatedItems": false
        },
        "note": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/note.json"
            },
            "unevaluatedItems": false
        },
        "bib": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/bib.json"
            },
            "unevaluatedItems": false
        },
        "cataloguer": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/change_log_entry"
            },
            "unevaluatedItems": false
        },
        "parent": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "internal": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "unevaluatedItems": false
        }
    },
    "required": [
        "ark",
        "reconstruction",
        "state",
        "label",
        "writing",
        "text_unit",
        "parent"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s19d0m.json
{
    "ark": "ark:/21198/s19d0m",
    "reconstruction": false,
    "label": "Sinai Syriac 164, Overtext (Melkite)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "melkite",
                    "label": "Melkite",
                    "writing_system": "Syriac"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1408z",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "13th c.",
            "iso": {
                "not_before": "1201",
                "not_after": "1300"
            }
        }
    ],
    "parent": [
        "ark:/21198/z1q5479k"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1z927.json
{
    "ark": "ark:/21198/s1z927",
    "reconstruction": false,
    "label": "Sinai Georgian 49, Undertext (Estrangela)",
    "locus": "ff. 17, 19, 22, 31â€“32, 38",
    "state": {
        "id": "undertext",
        "label": "Undertext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "estrangela",
                    "label": "Estrangela",
                    "writing_system": "Syriac"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1m971",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "5th-6th c. ",
            "iso": {
                "not_before": "0401",
                "not_after": "0600"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Description of undertext by Grigory Kessel"
        }
    ],
    "parent": [
        "ark:/21198/z12v3d24"
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/layers/s1gp5t.json
{
    "ark": "ark:/21198/s1gp5t",
    "reconstruction": false,
    "label": "Sinai Arabic 104, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s19642",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "deco-geometric",
            "label": "Decoration, Geometric"
        },
        {
            "id": "deco-vegetative",
            "label": "Decoration, Vegetative"
        },
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "f. 294r",
            "lang": [
                {
                    "id": "arab1395",
                    "label": "Arabic"
                }
            ],
            "as_written": "نجزت الاربعة مقالات المقدسة على تمامها وكمالها وكذلك عدد فصولها وكان الفراغ منها يوم الثلاثاء الرابع وعشرين من شهر حزيران سنة ست آلاف وسبعمائة تسعة وثمانين للعالم وذلك بجبل الله المقدس طور سيناء وهو برسم الشيخ أنبا ميخائيل الخمسي نفعه الله به وكل من قرأ فيه ودعا لناسخ الخاطئ بمغفرة خطاياه يكون له من السيد المسيح نظير ذلك والسبح لله دائما أبدا آمين ",
            "assoc_date": [
                {
                    "type": {
                        "id": "origin",
                        "label": "Date of Origin"
                    },
                    "value": "Tuesday 14 Huzayran 6789 (world)"
                }
            ],
            "note": [
                "Attested places:  Mount Sinai"
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "1281",
            "iso": {
                "not_before": "1281"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Ornate geometric headpiece, f. 135r, cross and knot motif, f. 1r ascending knots; f. 83r, knot motif with fleur de lis; f. 225r, vegetative and fleur de lis motif"
        }
    ],
    "parent": [
        "ark:/21198/z1x36g3q"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s13p75.json
{
    "ark": "ark:/21198/s13p75",
    "reconstruction": false,
    "label": "Sinai Syriac 189, Overtext (Melkite)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "melkite",
                    "label": "Melkite",
                    "writing_system": "Syriac"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1x952",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        },
        {
            "id": "deco-geometric",
            "label": "Decoration, Geometric"
        },
        {
            "id": "deco-zoomorph",
            "label": "Decoration, Zoomorphic"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "13th c.",
            "iso": {
                "not_before": "1201",
                "not_after": "1300"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Minor geometric headpieces throughout, beginning on f. 27v | Zoomorphic headpiece, f. 171r, intertwined serpents"
        }
    ],
    "parent": [
        "ark:/21198/z14f2v32"
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/layers/s1fp78.json
{
    "ark": "ark:/21198/s1fp78",
    "reconstruction": false,
    "label": "Sinai Greek NF MG 29, Undertext (Greek majuscule)",
    "locus": "throughout ff. 1â€“46",
    "state": {
        "id": "undertext",
        "label": "Undertext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "greek-maj",
                    "label": "Greek majuscule",
                    "writing_system": "Greek"
                }
            ],
            "note": [
                "Alexandrian majuscule | Unimodular majuscule"
            ]
        }
    ],
    "layout": [
        {
            "columns": "1 columns",
            "lines": "20 lines"
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s13q30",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "2nd half 6th c. ",
            "iso": {
                "not_before": "0551",
                "not_after": "0600"
            }
        }
    ],
    "assoc_place": [
        {
            "value": "Egypt",
            "event": {
                "id": "origin",
                "label": "Place of Origin"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "Reconstructed folio order, ff. Frg. 4v, frg. 4r, frg. 3r, frg. 3v, fol. 27r, fol. 27v, fol. 5r, fol. 5v, fol. 21r, fol. 21v, fol. 22r, fol. 22v, frg. 19v,  frg. 19r, fol. 24r, fol. 24v, fol. 19r, fol. 19v, fol. 16r, fol. 16v, fol. 32r, fol. 32v, fol. 29r, fol. 29v, frg. 12v, frg. 2v, frg. 12r, frg. 2r, fol. 15r, fol. 15v, fol. 17r, fol. 17v, frg. 8r, frg. 8v, frg. 7v, frg. 7r, fol. 31r, fol. 31v, fol. 30r, fol. 30v, frg. 24v, frg. 6v, frg. 24r, frg. 6r, fol. 37r, fol. 37v, fol. 40r, fol. 40v, fol. 26r, fol. 26v, fol. 43r,  fol. 43v, fol. 10r, fol. 10v, fol. 4r, fol. 4v, frg. 10v, frg. 10r, frg. 1v, frg. 1r, frg. 25r, frg. 25v, fol. 6r, fol. 6v, fol. 13r, fol. 13v, fol. 11r, fol. 11v, fol. 45v, fol. 45r, fol. 12r, fol. 12v, fol. 46r, fol. 46v, fol. 3r, fol. 3v, f. 35r, fol. 35v, fol. 41r, fol. 41v, fol. 7v, fol. 7r, fol. 28r, fol. 28v, frg. 11r, frg. 17r, frg. 11v, frg. 17v, fol. 18r, fol. 18v, fol. 14r, fol. 14v, fol. 25r, fol. 25v, fol. 39r, fol. 39v, fol. 8r, fol. 8v, fol. 34r, fol. 34v, fol. 9r, fol. 9v, fol. 44r, fol. 44v, fol. 38r, fol. 38v, fol. 33r, fol. 33v, fol. 20r, fol. 20v, fol. 36r, fol. 36v, fol. 42r, fol. 42v, fol. 23r, fol. 23v"
        },
        {
            "type": {
                "id": "general",
                "label": "Other Notes"
            },
            "value": "Description of undertext by Pasquale Orsini"
        }
    ],
    "parent": [
        "ark:/21198/z1kp8b5g"
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/layers/s1q909.json
{
    "ark": "ark:/21198/s1q909",
    "reconstruction": false,
    "label": "Sinai Arabic 532, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1hw8b",
            "label": "Item 1"
        }
    ],
    "features": [
        {
            "id": "dated",
            "label": "Dated"
        },
        {
            "id": "headpiece",
            "label": "Headpiece(s)"
        },
        {
            "id": "deco-vegetative",
            "label": "Decoration, Vegetative"
        },
        {
            "id": "colophon",
            "label": "Colophon"
        }
    ],
    "para": [
        {
            "type": {
                "id": "colophon",
                "label": "Colophon"
            },
            "locus": "f. 178v",
            "lang": [
                {
                    "id": "arab1395",
                    "label": "Arabic"
                }
            ],
            "as_written": "نجزت القصة المباركة يوم الاثنين التاسع وعشرين من أيلول سنة ست ألف وسبعمائه وخمسة وأربعين للعالم",
            "assoc_date": [
                {
                    "type": {
                        "id": "origin",
                        "label": "Date of Origin"
                    },
                    "value": "Tuesday 29 Aylul 6745"
                }
            ]
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "1237",
            "iso": {
                "not_before": "1237"
            }
        }
    ],
    "note": [
        {
            "type": {
                "id": "ornamentation",
                "label": "Ornamentation Note"
            },
            "value": "Vegetative headpiece on f. 2v"
        }
    ],
    "parent": [
        "ark:/21198/z14t7nnf"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s12s4r.json
{
    "ark": "ark:/21198/s12s4r",
    "reconstruction": false,
    "label": "Sinai Arabic 253, Overtext (Naskh)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "naskh",
                    "label": "Naskh",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1wd31",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "13th c.",
            "iso": {
                "not_before": "1201",
                "not_after": "1300"
            }
        }
    ],
    "parent": [
        "ark:/21198/z1989rrt"
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/layers/s1jw3r.json
{
    "ark": "ark:/21198/s1jw3r",
    "reconstruction": false,
    "label": "Sinai Arabic 461, Overtext (Kufic)",
    "state": {
        "id": "overtext",
        "label": "Overtext"
    },
    "writing": [
        {
            "script": [
                {
                    "id": "kufic",
                    "label": "Kufic",
                    "writing_system": "Arabic"
                }
            ]
        }
    ],
    "text_unit": [
        {
            "id": "ark:/21198/s1ch3d",
            "label": "Item 1"
        }
    ],
    "assoc_date": [
        {
            "type": {
                "id": "origin",
                "label": "Date of Origin"
            },
            "value": "10th c.",
            "iso": {
                "not_before": "0901",
                "not_after": "1000"
            }
        }
    ],
    "parent": [
        "ark:/21198/z1v13pjk"
    ]
}
