=== UCLALibrary/sinai_metadata/data-model/jsonschemas/ms_obj.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/ms_obj.json",
    "title": "Manuscript Object",
    "description": "A manuscript or codex, either real or a hypothetical reconstruction",
    "type": "object",
    "properties": {
        "ark": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
        },
        "reconstruction": {
            "type": "boolean"
        },
        "type": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
        },
        "shelfmark": {
            "type": "string",
            "minLength": 1
        },
        "summary": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/summary"
        },
        "extent": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/extent"
        },
        "weight": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/weight"
        },
        "dim": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/dim"
        },
        "state": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/states"
        },
        "fol": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/fol"
        },
        "coll": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/coll"
        },
        "features": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
            },
            "unevaluatedItems": false
        },
        "part": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/part.json"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "layer": {
            "type": ["array"],
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                    },
                    "label": {
                        "type": "string",
                        "minLength": 1
                    },
                    "type": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term",
                        "enums": [
                            {
                                "id": "undertext",
                                "label": "Undertext"
                            },
                            {
                                "id": "guest",
                                "label": "Guest Content"
                            }
                        ]
                    },
                    "locus": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
                    }
                },
                "required": [
                    "id",
                    "label",
                    "type"
                ],
                "unevaluatedProperties": false
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "para": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/paracontent.json"
            },
            "unevaluatedItems": false
        },
        "location": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ms_location"
            },
            "unevaluatedItems": false
        },
        "assoc_date": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_date.json"
            },
            "unevaluatedItems": false
        },
        "assoc_name": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_name.json"
            },
            "unevaluatedItems": false
        },
        "assoc_place": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_place.json"
            },
            "unevaluatedItems": false
        },
        "note": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/note.json"
            },
            "unevaluatedItems": false
        },
        "related_mss": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/related_mss.json"
            },
            "unevaluatedItems": false
        },
        "viscodex": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/viscodex.json"
            },
            "unevaluatedItems": false
        },
        "bib": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/bib.json"
            },
            "unevaluatedItems": false
        },
        "iiif": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/iiif.json"
            },
            "unevaluatedItems": false
        },
        "internal": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "unevaluatedItems": false
        },
        "desc_provenance": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/desc_provenance"
        },
        "image_provenance": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/image_provenance"
        },
        "cataloguer": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/change_log_entry"
            },
            "unevaluatedItems": false
        },
        "reconstructed_from": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
            },
            "unevaluatedItems": false
        }
    },
    "required": [
        "ark",
        "reconstruction",
        "type",
        "shelfmark",
        "extent",
        "state",
        "part",
        "location"
    ],
    "unevaluatedProperties": false,
    "if": {
        "properties": {
            "reconstruction": {"const": true}
        },
        "required": ["reconstruction"]
    },
    "then": {
        "properties": {
            "type": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/ms_obj_reconstructed_types"
            },
            "reconstructed_from": {
                "type": "array",
                "items": {
                    "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                },
                "unevaluatedItems": false
            }
        },
        "required": ["reconstructed_from"]
    },
    "else": {
        "properties": {
            "type": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/ms_obj_real_types"
            }
        }
    }
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1sj2pw7.json
{
    "ark": "ark:/21198/z1sj2pw7",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 454",
    "extent": "67 ff.",
    "weight": "574.1 g",
    "dim": "253 x 185 x 49 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s16p6q",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "para",
                "label": "Paracontent Note"
            },
            "value": "Multiple inscriptions on last folio (recto and verso)"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[408], p. 32"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "http://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1sj2pw7/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1rn510k.json
{
    "ark": "ark:/21198/z1rn510k",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Syriac NF M 63",
    "extent": "4 ff.",
    "weight": "18.1 g",
    "dim": "210 x 152 x 7.0 mm",
    "state": {
        "id": "bifolio",
        "label": "Bifolio(s)"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "parchment",
                    "label": "Parchment"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1nw5f",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ],
            "related_mss": [
                {
                    "type": {
                        "id": "disjecta",
                        "label": "Disjecta Membra"
                    },
                    "label": "Originally belonged together with Syriac 50; Syriac NF M 50; and Milan, Biblioteca Ambrosiana, A 296 inf., ff. 214–216, 219–221 (= Chabot 75)",
                    "note": [
                        "nan"
                    ],
                    "mss": [
                        {
                            "label": "Sinai Syriac 50",
                            "id": "ark:/21198/z1s489m7"
                        },
                        {
                            "label": "Sinai Syriac NF M 50",
                            "id": "ark:/21198/z1jq49kz"
                        },
                        {
                            "label": "Milan (Chabot 75)"
                        }
                    ]
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-nf",
            "collection": "New Finds",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "220eeb5e-ef2f-4ddd-96e5-47e2220aa409",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[M63N], p. 557"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1rn510k/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1p28qb0%2Fr9217z49/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1989wgw.json
{
    "ark": "ark:/21198/z1989wgw",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 4",
    "extent": "281 ff.",
    "weight": "1561 g",
    "dim": "268 x 176 x 83.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s12w21",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[4], p. 11"
        },
        {
            "id": "ec7c937f-655a-4459-b327-3793637b9db9",
            "type": {
                "id": "otherdigversion",
                "label": "Other Digital Version"
            },
            "alt_shelf": "https://www.loc.gov/item/00279385731-ms/",
            "url": "nan"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1989wgw/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1989wgw%2F1z449m5f/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1zk6kz9.json
{
    "ark": "ark:/21198/z1zk6kz9",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 435",
    "extent": "253 ff.",
    "weight": "772.0 g",
    "dim": "172 x 138 x 376 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s18k69",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    }
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "Back pastedown is foliated as f. 254"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[490], p. 39"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "http://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1zk6kz9/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1zk6kz9%2Frq51tn6g/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1fn35q3.json
{
    "ark": "ark:/21198/z1fn35q3",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic NF X 6",
    "extent": "143 ff.",
    "weight": "384.4 g",
    "dim": "170 x 140 x 65.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s19g8b",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    }
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-nf",
            "collection": "New Finds",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "cb8b8b52-569b-4d1f-8d5c-adf911afd205",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "p. 38; ٤٠"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1fn35q3/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1fn35q3%2Ffw58dg6n/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1kd3gkv.json
{
    "ark": "ark:/21198/z1kd3gkv",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Syriac 166",
    "extent": "242 ff.",
    "weight": "679.6 g",
    "dim": "147 x 123 x 85.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s11w5v",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "Ff. 39, 62, 105, 121, 132, 152, 185, 236, 240, 245, 251 stuck together; ff. 92, 93 split"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[116], p. 155"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1kd3gkv/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1kd3gkv%2F13084j5c/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1x07rnj.json
{
    "ark": "ark:/21198/z1x07rnj",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 482",
    "extent": "300 ff.",
    "weight": "1526 g",
    "dim": "247 x 189 x 79 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1rg8c",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[417], p. 33"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1x07rnj/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1x07rnj%2F5h98942r/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1n02zkr.json
{
    "ark": "ark:/21198/z1n02zkr",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic NF M 28",
    "extent": "16 ff.",
    "weight": "40.1 g",
    "dim": "192 x 140 x 20.0 mm",
    "state": {
        "id": "quire",
        "label": "Quire(s)"
    },
    "coll": "Quires 1-2: 2x8 (16)",
    "features": [
        {
            "id": "palimpsest",
            "label": "Palimpsest"
        }
    ],
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "parchment",
                    "label": "Parchment"
                }
            ],
            "dim": "191 x 137 mm (representative folio)",
            "layer": [
                {
                    "id": "ark:/21198/s1j62g",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                },
                {
                    "id": "ark:/21198/s1fk90",
                    "label": "Greek Undertext: Bible. Genesis",
                    "type": {
                        "id": "undertext",
                        "label": "Undertext"
                    },
                    "locus": "ff. 131–132v, 138, 140–142"
                },
                {
                    "id": "ark:/21198/s19w6q",
                    "label": "Greek Undertext: Exodus",
                    "type": {
                        "id": "undertext",
                        "label": "Undertext"
                    },
                    "locus": "ff. 128–130v, 133–137, 139, 143"
                }
            ],
            "related_mss": [
                {
                    "type": {
                        "id": "disjecta",
                        "label": "Disjecta Membra"
                    },
                    "label": "Originally belonged to the same manuscript as Arabic NF M 8 and Arabic NF M 27",
                    "note": [
                        "Text continues from Arabic NF M 8"
                    ],
                    "mss": [
                        {
                            "label": "Sinai Arabic NF M 8",
                            "id": "ark:/21198/z1kd1z25"
                        }
                    ]
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-nf",
            "collection": "New Finds",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "Pencil foliation begins with fol. 128"
        },
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "Two unsewn quires"
        }
    ],
    "bib": [
        {
            "id": "cb8b8b52-569b-4d1f-8d5c-adf911afd205",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "p. 29;  ٢٧"
        },
        {
            "id": "ebe32f6b-ad60-472c-aceb-d86913448530",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "pp. 28-57"
        },
        {
            "id": "01d4a639-d314-4271-b7f8-3f559c6c744c",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "p. 76"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1n02zkr/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1n02zkr%2Fq878hh1t/full/!200,200/0/default.jpg"
        }
    ]
}
