=== UCLALibrary/sinai_metadata/data-model/jsonschemas/ms_obj.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/ms_obj.json",
    "title": "Manuscript Object",
    "description": "A manuscript or codex, either real or a hypothetical reconstruction",
    "type": "object",
    "properties": {
        "ark": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
        },
        "reconstruction": {
            "type": "boolean"
        },
        "type": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
        },
        "shelfmark": {
            "type": "string",
            "minLength": 1
        },
        "summary": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/summary"
        },
        "extent": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/extent"
        },
        "weight": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/weight"
        },
        "dim": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/dim"
        },
        "state": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/states"
        },
        "fol": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/fol"
        },
        "coll": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/coll"
        },
        "features": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
            },
            "unevaluatedItems": false
        },
        "part": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/part.json"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "layer": {
            "type": ["array"],
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                    },
                    "label": {
                        "type": "string",
                        "minLength": 1
                    },
                    "type": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term",
                        "enums": [
                            {
                                "id": "undertext",
                                "label": "Undertext"
                            },
                            {
                                "id": "guest",
                                "label": "Guest Content"
                            }
                        ]
                    },
                    "locus": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
                    }
                },
                "required": [
                    "id",
                    "label",
                    "type"
                ],
                "unevaluatedProperties": false
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "para": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/paracontent.json"
            },
            "unevaluatedItems": false
        },
        "location": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ms_location"
            },
            "unevaluatedItems": false
        },
        "assoc_date": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_date.json"
            },
            "unevaluatedItems": false
        },
        "assoc_name": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_name.json"
            },
            "unevaluatedItems": false
        },
        "assoc_place": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_place.json"
            },
            "unevaluatedItems": false
        },
        "note": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/note.json"
            },
            "unevaluatedItems": false
        },
        "related_mss": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/related_mss.json"
            },
            "unevaluatedItems": false
        },
        "viscodex": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/viscodex.json"
            },
            "unevaluatedItems": false
        },
        "bib": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/bib.json"
            },
            "unevaluatedItems": false
        },
        "iiif": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/iiif.json"
            },
            "unevaluatedItems": false
        },
        "internal": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "unevaluatedItems": false
        },
        "desc_provenance": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/desc_provenance"
        },
        "image_provenance": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/image_provenance"
        },
        "cataloguer": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/change_log_entry"
            },
            "unevaluatedItems": false
        },
        "reconstructed_from": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
            },
            "unevaluatedItems": false
        }
    },
    "required": [
        "ark",
        "reconstruction",
        "type",
        "shelfmark",
        "extent",
        "state",
        "part",
        "location"
    ],
    "unevaluatedProperties": false,
    "if": {
        "properties": {
            "reconstruction": {"const": true}
        },
        "required": ["reconstruction"]
    },
    "then": {
        "properties": {
            "type": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/ms_obj_reconstructed_types"
            },
            "reconstructed_from": {
                "type": "array",
                "items": {
                    "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                },
                "unevaluatedItems": false
            }
        },
        "required": ["reconstructed_from"]
    },
    "else": {
        "properties": {
            "type": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/ms_obj_real_types"
            }
        }
    }
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z14j1zq1.json
{
    "ark": "ark:/21198/z14j1zq1",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 474",
    "extent": "329 ff.",
    "weight": "1470.9 g",
    "dim": "223 x 188 x 93 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1np6r",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    }
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[502], p. 41"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz14j1zq1/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz14j1zq1%2F8x80cj5b/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z19k5vzb.json
{
    "ark": "ark:/21198/z19k5vzb",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Syriac 42",
    "extent": "279 ff.",
    "weight": "917.1 g",
    "dim": "172 x 131 x 78.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                },
                {
                    "id": "parchment",
                    "label": "Parchment"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1kd03",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "support",
                "label": "Support Note"
            },
            "value": "Ff. 190-220, 226-241 are parchment"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[147], p. 157"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz19k5vzb/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz19k5vzb%2Fm0373187/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1st8t3m.json
{
    "ark": "ark:/21198/z1st8t3m",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 499",
    "extent": "203 ff.",
    "weight": "591.1 g",
    "dim": "182 x 161 x 62 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1pg7c",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "Foliation starts from f. 7"
        },
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "Ff. 1â€“6 apparently torn out/lost"
        },
        {
            "type": {
                "id": "contents",
                "label": "Contents Note"
            },
            "value": "Ff. 33v, back board inside filled with Arabic writing in a different hand"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[426], p. 34"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "http://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1st8t3m/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1st8t3m%2F5d33p893/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1np37q4.json
{
    "ark": "ark:/21198/z1np37q4",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 89",
    "extent": "240 ff.",
    "weight": "966.3 g",
    "dim": "189 x 144 x 70 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s11k5r",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "para",
                "label": "Paracontent Note"
            },
            "value": "Reader and supplicant inscriptions, f. 1r | Reader inscription, f. 193v | Inscription (Coptic?), f. 194v"
        },
        {
            "type": {
                "id": "foliation",
                "label": "Foliation Note"
            },
            "value": "ff. 202 and 223 lacking"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[82], p. 14"
        },
        {
            "id": "ec7c937f-655a-4459-b327-3793637b9db9",
            "type": {
                "id": "otherdigversion",
                "label": "Other Digital Version"
            },
            "url": "https://www.loc.gov/item/0027938670A-ms/"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "http://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1np37q4/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1np37q4%2F9c34v405/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1pg39cq.json
{
    "ark": "ark:/21198/z1pg39cq",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 238",
    "extent": "371 ff.",
    "weight": "1255.3 g",
    "dim": "181 x 148 x 92.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1rg70",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[297], p. 25"
        },
        {
            "id": "f3ea9df2-bf85-465c-ac1d-6bd4cce71e21",
            "type": {
                "id": "otherdigversion",
                "label": "Other Digital Version"
            },
            "alt_shelf": "https://www.nli.org.il/en/manuscripts/NNL_ALEPH990038714010205171//NLI",
            "url": "nan"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1pg39cq/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1pg39cq%2Fg228zw0g/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/data-model/tnb_docs/sample_records/ms_objs/z1dj76t1.json
{
    "ark": "ark:/21198/z1dj76t1",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 481",
    "extent": "338 ff.",
    "weight": "2754.9 g",
    "dim": "268 x 199 x 128.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1w60t",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    }
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[416], p. 33"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1dj76t1/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1dj76t1%2F3942m48n/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z15b1m5z.json
{
    "ark": "ark:/21198/z15b1m5z",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Syriac 6",
    "extent": "170 ff.",
    "weight": "1671.8 g",
    "dim": "244 x 204 x 90.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "parchment",
                    "label": "Parchment"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s16911",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "contents",
                "label": "Contents Note"
            },
            "value": "Palimpsests throughout"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[77], p. 154"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz15b1m5z/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz15b1m5z%2Fj207dp4s/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1qv5574.json
{
    "ark": "ark:/21198/z1qv5574",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 442",
    "extent": "317 ff.",
    "weight": "1202.6 g",
    "dim": "189 x 145 x 92 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1h31r",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[518], p. 43"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1qv5574/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1qv5574%2Ftm56qt3q/full/!200,200/0/default.jpg"
        }
    ]
}
