=== UCLALibrary/sinai_metadata/data-model/jsonschemas/ms_obj.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/ms_obj.json",
    "title": "Manuscript Object",
    "description": "A manuscript or codex, either real or a hypothetical reconstruction",
    "type": "object",
    "properties": {
        "ark": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
        },
        "reconstruction": {
            "type": "boolean"
        },
        "type": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
        },
        "shelfmark": {
            "type": "string",
            "minLength": 1
        },
        "summary": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/summary"
        },
        "extent": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/extent"
        },
        "weight": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/weight"
        },
        "dim": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/dim"
        },
        "state": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/states"
        },
        "fol": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/fol"
        },
        "coll": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/coll"
        },
        "features": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term"
            },
            "unevaluatedItems": false
        },
        "part": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/part.json"
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "layer": {
            "type": ["array"],
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                    },
                    "label": {
                        "type": "string",
                        "minLength": 1
                    },
                    "type": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/controlled_term",
                        "enums": [
                            {
                                "id": "undertext",
                                "label": "Undertext"
                            },
                            {
                                "id": "guest",
                                "label": "Guest Content"
                            }
                        ]
                    },
                    "locus": {
                        "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/locus"
                    }
                },
                "required": [
                    "id",
                    "label",
                    "type"
                ],
                "unevaluatedProperties": false
            },
            "minItems": 1,
            "unevaluatedItems": false
        },
        "para": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/paracontent.json"
            },
            "unevaluatedItems": false
        },
        "location": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ms_location"
            },
            "unevaluatedItems": false
        },
        "assoc_date": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_date.json"
            },
            "unevaluatedItems": false
        },
        "assoc_name": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_name.json"
            },
            "unevaluatedItems": false
        },
        "assoc_place": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/assoc_place.json"
            },
            "unevaluatedItems": false
        },
        "note": {
            "type": ["array", "null"],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/note.json"
            },
            "unevaluatedItems": false
        },
        "related_mss": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/related_mss.json"
            },
            "unevaluatedItems": false
        },
        "viscodex": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/viscodex.json"
            },
            "unevaluatedItems": false
        },
        "bib": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/bib.json"
            },
            "unevaluatedItems": false
        },
        "iiif": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/iiif.json"
            },
            "unevaluatedItems": false
        },
        "internal": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "unevaluatedItems": false
        },
        "desc_provenance": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/desc_provenance"
        },
        "image_provenance": {
            "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/image_provenance"
        },
        "cataloguer": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/change_log_entry"
            },
            "unevaluatedItems": false
        },
        "reconstructed_from": {
            "type": "array",
            "items": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
            },
            "unevaluatedItems": false
        }
    },
    "required": [
        "ark",
        "reconstruction",
        "type",
        "shelfmark",
        "extent",
        "state",
        "part",
        "location"
    ],
    "unevaluatedProperties": false,
    "if": {
        "properties": {
            "reconstruction": {"const": true}
        },
        "required": ["reconstruction"]
    },
    "then": {
        "properties": {
            "type": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/ms_obj_reconstructed_types"
            },
            "reconstructed_from": {
                "type": "array",
                "items": {
                    "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/utils.json#/$defs/ark"
                },
                "unevaluatedItems": false
            }
        },
        "required": ["reconstructed_from"]
    },
    "else": {
        "properties": {
            "type": {
                "$ref": "https://raw.githubusercontent.com/UCLALibrary/sinai_metadata/master/data-model/jsonschemas/enums.json#/$defs/ms_obj_real_types"
            }
        }
    }
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1669xxh.json
{
    "ark": "ark:/21198/z1669xxh",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Syriac 174",
    "extent": "191 ff.",
    "weight": "586 g",
    "dim": "156 x 116 x 78.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s18g9d",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[158], p. 157"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1669xxh/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1669xxh%2Fx964154p/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1zg8rqz.json
{
    "ark": "ark:/21198/z1zg8rqz",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Syriac NF X 5",
    "extent": "58 ff.",
    "weight": "211.6 g",
    "dim": "178 x 145 x 24.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1f92k",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    }
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-nf",
            "collection": "New Finds",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "The front pastedown consists of three leaves glued together"
        }
    ],
    "bib": [
        {
            "id": "220eeb5e-ef2f-4ddd-96e5-47e2220aa409",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[X5N], pp. 109-113"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1zg8rqz/manifest",
            "text_direction": "right-to-left",
            "behavior": "individuals",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1zg8rqz%2F03630k90/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1jm404c.json
{
    "ark": "ark:/21198/z1jm404c",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 704",
    "extent": "103 ff.",
    "weight": "162.7 g",
    "dim": "157 x 107 x 22.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1332d",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    }
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1jm404c/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1jm404c%2F6r37kq89/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1960050.json
{
    "ark": "ark:/21198/z1960050",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Georgian NF frag 68a",
    "extent": "1 ff.",
    "dim": "145 x 106 mm",
    "state": {
        "id": "folio-fragment",
        "label": "Folio Fragment(s)"
    },
    "features": [
        {
            "id": "palimpsest",
            "label": "Palimpsest"
        },
        {
            "id": "msi",
            "label": "Multispectral Imaging"
        }
    ],
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "parchment",
                    "label": "Parchment"
                }
            ],
            "dim": "145 x 106 mm (representative folio)",
            "layer": [
                {
                    "id": "ark:/21198/s10w5j",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                },
                {
                    "id": "ark:/21198/s16g9s",
                    "label": "CPA Undertext: Ephrem Graecus, On the Antichrist",
                    "type": {
                        "id": "undertext",
                        "label": "Undertext"
                    },
                    "locus": "f. 1"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-nf",
            "collection": "New Finds",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "binding",
                "label": "Binding Note"
            },
            "value": "Binding absent"
        },
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "The parchment is fragile; all four sides are now irregular, with some splitting to the parchment along the ruled lines of the undertext, and losses to the inner areas of the leaf; dirt adheres to areas of the verso"
        }
    ],
    "bib": [
        {
            "id": "8eab4b8e-e5d8-40c6-9a5f-70748ca6d41e",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "pp. 482-494"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://sinai-images.library.ucla.edu/iiif/ark:%2F21198%2Fz1960050/manifest",
            "behavior": "paged",
            "thumbnail": "https://sinai-images.library.ucla.edu/iiif/ark:%2F21198%2Fz10v8vhm/0,1022,6132,6132/150,150/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1184r68.json
{
    "ark": "ark:/21198/z1184r68",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 323",
    "extent": "314 ff.",
    "weight": "1166.2 g",
    "dim": "188 x 141 x 85 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1xs5w",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "Some split pages"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[514], p. 43"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://iiif.library.ucla.edu/ark%3A%2F21198%2Fz1184r68/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1184r68%2Fr452fc40/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1fx8v69.json
{
    "ark": "ark:/21198/z1fx8v69",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 217",
    "extent": "139 ff.",
    "weight": "432.7 g",
    "dim": "146 x 153 x 65.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s16p5b",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[288], p. 24"
        },
        {
            "id": "f3ea9df2-bf85-465c-ac1d-6bd4cce71e21",
            "type": {
                "id": "otherdigversion",
                "label": "Other Digital Version"
            },
            "url": "https://www.nli.org.il/en/manuscripts/NNL_ALEPH990038916620205171//NLI"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1fx8v69/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1fx8v69%2Fbt08bv8s/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1v13pjk.json
{
    "ark": "ark:/21198/z1v13pjk",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Arabic 461",
    "extent": "117 ff.",
    "weight": "789.6 g",
    "dim": "215 x 179 x 67.0 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "parchment",
                    "label": "Parchment"
                }
            ],
            "layer": [
                {
                    "id": "ark:/21198/s1jw3r",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    },
                    "locus": "<NA>"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "Ff. 26, 31 sewn together"
        },
        {
            "type": {
                "id": "contents",
                "label": "Contents Note"
            },
            "value": "Erased text f. 25av, 25br ; suspected palimpsest 25av"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[521], p. 43"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://ingest.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1v13pjk/manifest",
            "text_direction": "right-to-left",
            "behavior": "paged",
            "thumbnail": "https://iiif.sinaimanuscripts.library.ucla.edu/iiif/2/ark%3A%2F21198%2Fz1v13pjk%2Fhh630t2s/full/!200,200/0/default.jpg"
        }
    ]
}

=== UCLALibrary/sinai_metadata/portal_data/ms_objs/z1ks7pg9.json
{
    "ark": "ark:/21198/z1ks7pg9",
    "reconstruction": false,
    "type": {
        "id": "manuscript",
        "label": "Manuscript"
    },
    "shelfmark": "Sinai Greek 2053",
    "extent": "34 ff.",
    "dim": "101 x 74 x 13 mm",
    "state": {
        "id": "codex",
        "label": "Codex"
    },
    "coll": "1+1 (2); Quire 1: 1x2 (4); Quire 2-3: 2x6 (16); Quire 4: 1x8 (24); Quire 5: 1x4 (28); Quire 6: 1x8-2 (34)",
    "features": [
        {
            "id": "palimpsest",
            "label": "Palimpsest"
        },
        {
            "id": "msi",
            "label": "Multispectral Imaging"
        }
    ],
    "part": [
        {
            "label": "Codicological Unit",
            "support": [
                {
                    "id": "parchment",
                    "label": "Parchment"
                },
                {
                    "id": "paper",
                    "label": "Paper"
                }
            ],
            "dim": "101 x 74 mm (representative folio)",
            "layer": [
                {
                    "id": "ark:/21198/s1x04k",
                    "label": "Overtext Layer",
                    "type": {
                        "id": "overtext",
                        "label": "Overtext"
                    }
                },
                {
                    "id": "ark:/21198/s1dw71",
                    "label": "Greek Undertext: Bible. Psalms, Psalter",
                    "type": {
                        "id": "undertext",
                        "label": "Undertext"
                    },
                    "locus": "ff. 1, 2r, 3–16"
                },
                {
                    "id": "ark:/21198/s1963p",
                    "label": "Greek Undertext: Synaxarion",
                    "type": {
                        "id": "undertext",
                        "label": "Undertext"
                    },
                    "locus": "ff. 17–24"
                },
                {
                    "id": "ark:/21198/s15d24",
                    "label": "Greek Undertext: Liturgical hymns",
                    "type": {
                        "id": "undertext",
                        "label": "Undertext"
                    },
                    "locus": "ff. 25–28"
                }
            ]
        }
    ],
    "location": [
        {
            "id": "sinai-oc",
            "collection": "Old Collection",
            "repository": "St. Catherine's Monastery of the Sinai"
        }
    ],
    "note": [
        {
            "type": {
                "id": "support",
                "label": "Support Note"
            },
            "value": "Last quire is paper"
        },
        {
            "type": {
                "id": "binding",
                "label": "Binding Note"
            },
            "value": "Sewing intact, but boards missing and spine uncovered"
        },
        {
            "type": {
                "id": "condition",
                "label": "Condition Note"
            },
            "value": "Opens easily, but an imperfect glue repair at ff. 4v/5r is causing f. 4 to tear | Discoloration through use in lower outer edges"
        }
    ],
    "bib": [
        {
            "id": "deb668b6-feec-4828-8749-a97441881226",
            "type": {
                "id": " ref",
                "label": "Reference"
            },
            "range": "[347], p. 74"
        }
    ],
    "iiif": [
        {
            "type": {
                "id": "main",
                "label": "Main"
            },
            "manifest": "https://sinai-images.library.ucla.edu/iiif/ark:%2F21198%2Fz1ks7pg9/manifest",
            "behavior": "paged",
            "thumbnail": "https://sinai-images.library.ucla.edu/iiif/ark:%2F21198%2Fz18k86rm/0,1022,6132,6132/150,150/0/default.jpg"
        }
    ]
}
